
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######



\COPY prices (company_id, current_price) FROM './seeds/prices_1.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_0.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_2.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_3.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_4.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_5.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_6.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_7.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_8.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_9.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_10.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_11.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_12.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_13.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_14.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_15.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_16.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_17.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_19.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_18.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_21.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_20.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_22.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_24.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_23.csv' CSV HEADER;
\COPY prices (company_id, current_price) FROM './seeds/prices_25.csv' CSV HEADER;
CREATE INDEX comp_id2 ON prices (company_id);
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_0.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_1.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_3.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_2.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_4.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_5.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_6.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_7.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_8.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_9.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_10.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_11.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_12.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_13.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_14.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_15.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_16.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_17.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_18.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_19.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_20.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_21.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_22.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_23.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_24.csv' CSV HEADER;
\COPY alsobought (company_id, alsobought_id) FROM './seeds/alsobought_25.csv' CSV HEADER;
CREATE INDEX comp_id1 ON alsobought (company_id);
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_0.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_1.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_2.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_4.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_3.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_5.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_6.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_8.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_7.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_10.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_9.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_11.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_12.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_13.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_14.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_16.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_15.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_17.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_18.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_19.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_20.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_21.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_22.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_23.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_25.csv' CSV HEADER;
\COPY companies (company_abbr, company, percentage) FROM './seeds/companies_24.csv' CSV HEADER;
CREATE INDEX abbr ON companies USING HASH (company_abbr);
