const fs = require('fs');

const header = `
/*
 *****************************************
 **                                     **
 **        Script Generated by:         **
 **           makeServers.js            **
 **                                     **
 *****************************************
*/\n
`;

const body = port => `const express = require('express');
const parser = require('body-parser');
const router = require('./routes');

const server = express();
server.use(parser.json());
server.use('/api', router);
server.set('PORT', ${port});
server.listen(server.get('PORT'), () => {
  console.log(\`Server is connected to \${server.get('PORT')}!\`);
});\n`;

for (let i = 0; i < 4; i += 1) {
  fs.writeFile(`./server/server${i}.js`, header + body(3000 + i), (error) => {
    if (error) { console.log(error); }
  });
}
