
/*
 *****************************************
 **                                     **
 **        Script Generated by:         **
 **           makeServers.js            **
 **                                     **
 *****************************************
*/

const express = require('express');
const parser = require('body-parser');
const router = require('./routes');

const server = express();
server.use(parser.json());
server.use('/api', router);
server.set('PORT', 3001);
server.listen(server.get('PORT'), () => {
  console.log(`Server is connected to ${server.get('PORT')}!`);
});
