const fs = require('fs');

const filepath = './database/import.sql';

const append = (i, table, header) => {
  const data = `\\COPY ${table} (${header}) FROM './seeds/${table}_${i}.csv' CSV HEADER;\n`;
  fs.appendFile(filepath, data, (error) => {
    if (error) { console.log(error); }
  });
};

const header = `
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######\n\n\n
`;

fs.writeFile(filepath, header, (e) => {
  if (e) { console.log(e); }
  for (let i = 0; i < 26; i++) {
    append(i, 'companies', 'company_abbr, company, percentage');
    append(i, 'alsobought', 'company_id, alsobought_id');
    append(i, 'prices', 'company_id, current_price');
  }
});
