const fs = require('fs');

const filepath = './database/importC.sql';

const append = (i, path) => {
  const data = `COPY robinhood.${path} FROM './seeds/${path}_${384616 * i}.csv' WITH HEADER = TRUE AND QUOTE = '\`';\n`;
  fs.appendFile(filepath, data, (error) => {
    if (error) { console.log(error); }
  });
};

const header = `
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######\n\n\n
`;

fs.writeFile(filepath, header, (e) => {
  if (e) { console.log(e); }
  for (let i = 0; i < 26; i++) {
    append(i, 'alsobought');
  }
});
