
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######



\COPY companies FROM './seeds/companies_0' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_384616' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_769232' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_1153848' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_1538464' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_1923080' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_2307696' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_2692312' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_3461544' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_3076928' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_3846160' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_4230776' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_4615392' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_5000008' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_5384624' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_5769240' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_6153856' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_6538472' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_6923088' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_7307704' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_7692320' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_8461552' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_8076936' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_8846168' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_9230784' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/companies_9615400' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_0' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_384616' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_769232' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_1153848' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_1538464' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_1923080' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_2307696' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_2692312' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_3076928' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_3461544' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_3846160' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_4230776' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_4615392' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_5000008' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_5384624' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_5769240' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_6153856' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_6538472' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_6923088' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_7307704' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_7692320' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_8076936' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_8461552' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_8846168' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_9230784' WITH QUOTE AS '`' CSV HEADER;
\COPY companies FROM './seeds/alsobought_9615400' WITH QUOTE AS '`' CSV HEADER;
