
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######



COPY robinhood.alsobought FROM './seeds/alsobought_0.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_769232.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_1153848.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_1538464.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_384616.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_1923080.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_2307696.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_2692312.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_3076928.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_3461544.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_3846160.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_4615392.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_4230776.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_5000008.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_5384624.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_5769240.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_6153856.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_6923088.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_6538472.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_7307704.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_8076936.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_7692320.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_8461552.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_9230784.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_8846168.csv' WITH HEADER = TRUE AND QUOTE = '`';
COPY robinhood.alsobought FROM './seeds/alsobought_9615400.csv' WITH HEADER = TRUE AND QUOTE = '`';
