
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######



\COPY companies FROM './seeds/companies_0.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_0.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_0.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_1.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_1.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_1.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_2.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_2.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_2.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_3.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_3.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_3.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_4.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_4.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_4.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_5.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_5.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_5.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_6.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_6.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_6.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_7.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_7.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_7.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_8.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_8.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_9.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_8.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_9.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_10.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_9.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_10.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_10.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_11.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_11.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_11.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_12.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_12.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_12.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_13.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_13.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_13.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_14.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_14.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_14.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_15.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_15.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_15.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_16.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_16.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_16.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_17.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_17.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_17.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_18.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_18.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_18.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_19.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_19.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_19.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_20.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_20.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_20.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_21.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_21.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_22.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_21.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_22.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_22.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_23.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_23.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_23.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_24.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_24.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_24.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_25.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_25.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY prices FROM './seeds/prices_25.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
