
-- #######                                            #######
--   #######################################################
--   #########                                     #########
--   #########        Script Generated by:         #########
--   #########        generatedImportSchema.js     #########
--   #########                                     #########
--   #######################################################
-- #######                                            #######



\COPY companies FROM './seeds/companies_769232.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_1153848.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_0.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_384616.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_1538464.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_1923080.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_2307696.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_2692312.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_3076928.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_3461544.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_4615392.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_3846160.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_4230776.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_5000008.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_5384624.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_6153856.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_6538472.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_5769240.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_6923088.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_7307704.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_7692320.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_8076936.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_8461552.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_9230784.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_8846168.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY companies FROM './seeds/companies_9615400.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_0.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_384616.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_1153848.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_769232.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_1923080.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_2307696.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_1538464.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_2692312.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_3076928.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_3461544.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_3846160.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_4615392.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_4230776.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_5000008.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_5384624.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_5769240.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_6153856.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_6538472.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_6923088.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_7307704.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_7692320.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_8076936.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_8461552.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_8846168.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_9230784.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
\COPY alsobought FROM './seeds/alsobought_9615400.csv' WITH QUOTE AS '`' DELIMITER AS '|' CSV HEADER;
