const fs = require('fs');

const header = `
/*
 *****************************************
 **                                     **
 **        Script Generated by:         **
 **        generatedScripts.js          **
 **                                     **
 *****************************************
*/\n
`;


for (let i = 0; i < 26; i++) {
  const data = `const createTickers = require('./createTickers');\n\ncreateTickers(384616 * ${i}, 384616 * ${i + 1});\n`;
  fs.writeFile(`./dataGeneration/seed_${i}.js`, header + data, (err) => {
    if (err) { console.log(err); }
  });
}
